import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:odyssey/src/features/statistics/data/models/statistics_model.dart';

/// The client half of the statistics wire contract (audit A20).
///
/// Both sides had been checked against their own invented sample, so they could
/// disagree indefinitely without either suite noticing. The fixture parsed here
/// is generated by the backend's `StatisticsWireContractTests` from the real
/// DTOs with the API's real serializer options, so it is the server's actual
/// output rather than a guess at it.
///
/// Regenerate with, from the backend directory:
///
/// ```
/// ODYSSEY_WRITE_WIRE_FIXTURES=1 \
///   ODYSSEY_WIRE_FIXTURE_DIR=<this folder> \
///   dotnet test --filter FullyQualifiedName~Fixtures_can_be_regenerated
/// ```
void main() {
  Map<String, dynamic> fixture(String name) {
    final file = File('test/statistics/fixtures/$name');

    expect(file.existsSync(), isTrue,
        reason: 'the wire fixture is missing; regenerate it from the backend');

    return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  }

  group('overall statistics', () {
    test('every field the server sends is read', () {
      final stats = OverallStatistics.fromJson(fixture('overall_statistics.json'));

      // The six fields that had no @JsonKey, so the generated parser looked for
      // their Dart names and found nothing. A EUR payload became USD with an
      // empty breakdown and no excluded-expense warning - a total that looked
      // authoritative while being wrong.
      expect(stats.reportingCurrency, 'EUR');
      expect(stats.unconvertedExpenseCount, 2);
      expect(stats.destinationDataAvailable, isFalse);
      expect(stats.plannedDaysAhead, 7);
      expect(stats.tripTags, ['beach', 'family']);

      // Currency codes must survive the server's snake_case dictionary-key
      // policy. "usd" matches no currency this app knows.
      expect(stats.expenseTotalsByCurrency.keys.toSet(), {'EUR', 'USD'});
      expect(stats.expenseTotalsByCurrency['EUR'], 150.50);

      // And the fields that were already correct, so a rename on either side is
      // caught rather than half the contract being checked.
      expect(stats.totalTrips, 3);
      expect(stats.totalExpenseAmount, 150.50);
      expect(stats.totalDaysOfTravel, 21);
      expect(stats.countriesVisited, 0);
    });

    test('the headline total is named in its own currency', () {
      final stats = OverallStatistics.fromJson(fixture('overall_statistics.json'));

      // The specific failure this guards: 100 USD + 100 EUR shown as "$200",
      // a figure that is not an amount of money in any currency. The total
      // belongs to one named currency, and everything else is listed separately.
      expect(stats.reportingCurrency, isNotEmpty);
      expect(
        stats.totalExpenseAmount,
        stats.expenseTotalsByCurrency[stats.reportingCurrency],
      );
      expect(stats.unconvertedExpenseCount, greaterThan(0),
          reason: 'expenses outside the reporting currency must be counted, '
              'not folded in at a guessed rate');
    });
  });

  group('year in review', () {
    /// The backend's shape, as `YearInReviewDto` serializes it.
    Map<String, dynamic> serverPayload() => {
          'year': 2026,
          'trips_count': 4,
          'total_days': 30,
          'top_destinations': [
            {'destination': 'Kyoto', 'trip_count': 2, 'total_days': 12},
            {'destination': 'Lisbon', 'trip_count': 1, 'total_days': 6},
          ],
          'total_spent': 900.0,
          'reporting_currency': 'USD',
          'spend_by_currency': {'USD': 900.0, 'EUR': 120.0},
          'unconverted_expense_count': 1,
          'destination_data_available': true,
          'most_used_expense_category': 'food',
          'activities_count': 20,
          'memories_count': 8,
          'most_visited_month': 'July',
          'expenses_by_category': {'food': 400.0, 'transport': 500.0},
          'trips_by_month': {'July': 2, 'August': 2},
        };

    test('the backend payload decodes instead of throwing', () {
      // This used to throw a TypeError before the screen could render: the
      // client declared `total_trips` and `total_days_traveled` as required and
      // the server sends `trips_count` and `total_days`.
      final stats = YearInReviewStats.fromJson(serverPayload());

      expect(stats.year, 2026);
      expect(stats.totalTrips, 4);
      expect(stats.totalDaysTraveled, 30);
      expect(stats.totalActivities, 20);
      expect(stats.totalMemories, 8);
      expect(stats.mostActiveMonth, 'July');
      expect(stats.tripsByMonth, {'July': 2, 'August': 2});
    });

    test('destinations arrive as objects and are read as names', () {
      final stats = YearInReviewStats.fromJson(serverPayload());

      // The client declared these as plain strings; the server sends objects.
      expect(stats.topDestinations, ['Kyoto', 'Lisbon']);
      expect(stats.destinationDataAvailable, isTrue);
    });

    test('spending is named in its own currency', () {
      final stats = YearInReviewStats.fromJson(serverPayload());

      expect(stats.totalSpent, 900.0);
      expect(stats.reportingCurrency, 'USD');
      expect(stats.totalExpensesByCurrency, {'USD': 900.0, 'EUR': 120.0});
      expect(stats.unconvertedExpenseCount, 1);
    });

    test('a payload with no destinations says so rather than showing zero', () {
      final payload = serverPayload()
        ..['top_destinations'] = <dynamic>[]
        ..['destination_data_available'] = false;

      final stats = YearInReviewStats.fromJson(payload);

      // The screen asks this before offering a destination figure. An empty
      // list with the flag false means "not recorded", not "went nowhere".
      expect(stats.destinationDataAvailable, isFalse);
      expect(stats.topDestinations, isEmpty);
    });

    test('a field the server omits does not throw', () {
      // Every field is read defensively, because a payload missing one should
      // degrade the screen, not break it.
      final stats = YearInReviewStats.fromJson({'year': 2026});

      expect(stats.year, 2026);
      expect(stats.totalTrips, 0);
      expect(stats.topDestinations, isEmpty);
      expect(stats.reportingCurrency, 'USD');
    });
  });
}
