// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBDw-OPKZ1jGFvRuiYgTC87XQt7jo6cc',
    appId: '1:780629189564:web:9d59777e0a33191fe6c1b9',
    messagingSenderId: '780629189564',
    projectId: 'odyssey-67e9c',
    authDomain: 'odyssey-67e9c.firebaseapp.com',
    storageBucket: 'odyssey-67e9c.firebasestorage.app',
    measurementId: 'G-VJZPD5SEE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzGa2W1Eg8heaTgYkbH4XUrYznIWsiQis',
    appId: '1:780629189564:android:5ca6c84e5f366c05e6c1b9',
    messagingSenderId: '780629189564',
    projectId: 'odyssey-67e9c',
    storageBucket: 'odyssey-67e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQ6twOJYQFxWYmMYok3g6ETQq324LR-4',
    appId: '1:780629189564:ios:131fe0a94b82714de6c1b9',
    messagingSenderId: '780629189564',
    projectId: 'odyssey-67e9c',
    storageBucket: 'odyssey-67e9c.firebasestorage.app',
    iosClientId: '780629189564-qksirrfstodh0ku3u5qtjlgk9v9i08vn.apps.googleusercontent.com',
    iosBundleId: 'com.pranta.odyssey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQ6twOJYQFxWYmMYok3g6ETQq324LR-4',
    appId: '1:780629189564:ios:131fe0a94b82714de6c1b9',
    messagingSenderId: '780629189564',
    projectId: 'odyssey-67e9c',
    storageBucket: 'odyssey-67e9c.firebasestorage.app',
    iosClientId: '780629189564-qksirrfstodh0ku3u5qtjlgk9v9i08vn.apps.googleusercontent.com',
    iosBundleId: 'com.pranta.odyssey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeBDw-OPKZ1jGFvRuiYgTC87XQt7jo6cc',
    appId: '1:780629189564:web:6368879041ebb980e6c1b9',
    messagingSenderId: '780629189564',
    projectId: 'odyssey-67e9c',
    authDomain: 'odyssey-67e9c.firebaseapp.com',
    storageBucket: 'odyssey-67e9c.firebasestorage.app',
    measurementId: 'G-53250Y61R6',
  );
}
